{% set name = "jupyter_app_launcher" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 34045f8edf0fb22f60be687222dfd12f7e662f7cf1e5d0c3e0469b642af463ca

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - jupyter-app_launcher = jupyter_app_launcher.script:build_lite

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling >=1.5.0
    - jupyterlab >=4.0.0,<5
    - hatch-nodejs-version >=0.3.2
    - hatch-jupyter-builder

  run:
    - python >=3.7
    - jupyter_server >=2.0.1,<3
    - pyyaml
    - jupyter-server-proxy >=4.1.0,<5
    - jsonschema
    - tornado >6.0.1,<7
    - jupyter_core >=5.0.0,<6
    - requests

test:
  imports:
    - jupyter_app_launcher
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/trungleduc/jupyter_app_launcher
  summary: JupyterLab extension to create custom launcher entries.
  description: |
    jupyter_app_launcher helps users customize the JupyterLab launcher with a simple YAML file.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://jupyter-app-launcher.readthedocs.io/
  dev_url: https://github.com/trungleduc/jupyter_app_launcher

extra:
  recipe-maintainers:
    - trungleduc
